package app.tandem.receiver.crypto

import app.tandem.receiver.net.FrameWriter
import app.tandem.receiver.net.MessageType
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.ByteArrayOutputStream
import java.io.File

/**
 * Reproduces the authoritative interop vectors in `docs/VECTORS.md` at the
 * repository root, which are generated by the Swift reference implementation
 * (`TandemProtocol`, `CryptoTests.testPrintVectors`).
 *
 * The expectations are parsed out of that file rather than copied into this
 * source, so the Swift side remains the single origin: if the reference
 * regenerates different values, this test fails instead of silently agreeing
 * with a stale copy.
 *
 * Inputs are fixed by the document: `pin = "123456"`, the two nominal UUIDs,
 * `hostNonce = 16 × 0x01`, `deviceNonce = 16 × 0x02`, `secret = 32 × 0x03`.
 */
class InteropVectorsTest {
    private val pin = "123456"
    private val hostId = "11111111-1111-1111-1111-111111111111"
    private val deviceId = "22222222-2222-2222-2222-222222222222"
    private val hostNonce = ByteArray(16) { 0x01 }
    private val deviceNonce = ByteArray(16) { 0x02 }
    private val secret = ByteArray(32) { 0x03 }

    @Test
    fun `this receiver reproduces the swift reference vectors`() {
        val reference = parseReferenceVectors()

        val pinKey = PairingCrypto.pinKey(pin, deviceId, hostId)
        val host = SessionCipher.forHost(secret, hostNonce, deviceNonce)
        val envelope = host.seal(MessageType.PING, ByteArray(8))
        val wire = ByteArrayOutputStream().also { FrameWriter(it).writeFrame(MessageType.ENC, envelope) }

        val computed =
            linkedMapOf(
                "pinKey" to CryptoPrimitives.hex(pinKey),
                "pairProof" to
                    CryptoPrimitives.hex(PairingCrypto.pairProof(pinKey, hostNonce, deviceNonce)),
                "authProof" to
                    CryptoPrimitives.hex(PairingCrypto.authProof(secret, hostNonce, deviceNonce)),
                "authAckProof" to
                    CryptoPrimitives.hex(PairingCrypto.authAckProof(secret, hostNonce, deviceNonce)),
                "pairBox" to
                    CryptoPrimitives.hex(
                        PairingCrypto.sealPairBox(pinKey, hostNonce, deviceNonce, secret),
                    ),
                "key_h2r" to
                    CryptoPrimitives.hex(
                        SessionCipher.hostToReceiverKey(secret, hostNonce, deviceNonce),
                    ),
                "key_r2h" to
                    CryptoPrimitives.hex(
                        SessionCipher.receiverToHostKey(secret, hostNonce, deviceNonce),
                    ),
                "encFrame" to CryptoPrimitives.hex(wire.toByteArray()),
            )

        computed.forEach { (name, value) ->
            assertEquals("vector '$name' disagrees with the Swift reference", reference[name], value)
        }
        // Every name the reference publishes must be covered here, so a new
        // vector on the Swift side cannot go unchecked.
        assertEquals(reference.keys, computed.keys)
    }

    @Test
    fun `the receiver opens the reference ENC frame`() {
        val reference = parseReferenceVectors()
        val frame = CryptoPrimitives.unhex(reference.getValue("encFrame"))

        // Strip [u32 length][u8 type] to get the ENC payload.
        assertEquals(MessageType.ENC, frame[4])
        val envelope = frame.copyOfRange(5, frame.size)

        val receiver = SessionCipher.forReceiver(secret, hostNonce, deviceNonce)
        val (type, payload) = receiver.open(envelope)
        assertEquals(MessageType.PING, type)
        assertEquals(8, payload.size)
        assertTrue(payload.all { it.toInt() == 0 })
    }

    /**
     * Reads the `name hex` lines from the fenced block in the reference
     * document. The path is found by walking up from the module directory so
     * the test does not depend on Gradle's working directory.
     */
    private fun parseReferenceVectors(): Map<String, String> {
        val file = findReferenceFile()
        val lines = file.readLines()
        val start = lines.indexOfFirst { it.trim() == "```" }
        val end = lines.indexOfLast { it.trim() == "```" }
        assertTrue("no fenced vector block in ${file.path}", start in 0 until end)

        val vectors = linkedMapOf<String, String>()
        for (line in lines.subList(start + 1, end)) {
            val parts = line.trim().split(Regex("\\s+"))
            if (parts.size == 2 && parts[1].matches(HEX)) vectors[parts[0]] = parts[1]
        }
        assertTrue("no vectors parsed from ${file.path}", vectors.isNotEmpty())
        return vectors
    }

    private fun findReferenceFile(): File {
        var dir: File? = File(".").absoluteFile
        while (dir != null) {
            val candidate = File(dir, RELATIVE_PATH)
            if (candidate.isFile) return candidate
            dir = dir.parentFile
        }
        throw AssertionError(
            "cannot find $RELATIVE_PATH above ${File(".").absolutePath}; " +
                "the authoritative vectors are generated by the Swift reference implementation",
        )
    }

    private companion object {
        const val RELATIVE_PATH = "docs/VECTORS.md"
        val HEX = Regex("[0-9a-f]{32,}")
    }
}
